sudo: required

language:
   - python

services:
   - docker

env:
   global:
      - CLEAN_TRAVIS_TAG=${TRAVIS_TAG/[[:space:]]/}
      - COMMIT=${CLEAN_TRAVIS_TAG:-${TRAVIS_COMMIT:0:7}}

script:
   - .travis/build

after_success:
   - .travis/after_success
