name: rastervision-poc
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-11.8.0
dependencies:
  - python=3.9
  - gcc=12
  - gdal=3.5.3
  - cuda-toolkit
  - cudnn
  - pip:
      - -r requirements.txt